<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>_2048</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icon.png" />
    <None Remove="Icon2.png" />
    <None Remove="SadCinnamoroll.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="StartWindowImage.jpg" />
    <Resource Include="Icon.png" />
    <Resource Include="Icon2.png" />
    <Resource Include="SadCinnamoroll.png" />
  </ItemGroup>

</Project>
